### PR TITLE
Add links and stuff

### PR DESCRIPTION
**Pull request by MattTheNub**
For when <https://elementnet.github.io/graphics/> is visited

### CODE REVIEW

**Comment by radioblahaj** [comment]
Let me Review this.

**Review by radioblahaj — COMMENTED** [review]
Are you done?

**Comment by MattTheNub** [comment]
@redmangospros yes; I was just adding some additional things we needed

**Review by radioblahaj — APPROVED** [review]
Approved!

**Comment by MattTheNub** [comment]
Apparently graphics isn't on codeowners -facepalm-

**Pull request merged**
